---
- name: finalize | Checking If Initial Admin Password Exists No Docker
  stat: path="{{ jenkins_home_dir }}/secrets/initialAdminPassword"
  register: "jenkins_initial_password_check"
  #when: jenkins_config_info.disable_setup_wizard
  ignore_errors: yes
  notify:
    - 'restart jenkins'

- name: finalize | Capturing Initial Admin Password
  command: "cat {{ jenkins_home_dir }}/secrets/initialAdminPassword"
  register: "jenkins_initialAdminPassword"
  changed_when: false
  when: jenkins_initial_password_check.stat.exists and (not jenkins_config_info.disable_setup_wizard)


- name: finalize | Capturing Initial Admin Password -- Not Docker
  command: "cat /var/lib/jenkins/secrets/initialAdminPassword"
  register: "jenkins_initialAdminPassword"
  changed_when: false
  when: jenkins_initial_password_check.stat.exists
